/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDFULLSCREEN_AUTODEFS_H
#define S3EANDROIDFULLSCREEN_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDFULLSCREEN_NAME "s3eAndroidFullscreen"
#define S3E_EXT_ANDROIDFULLSCREEN_HASH 0x3bb5b1c4

#endif /* !S3EANDROIDFULLSCREEN_AUTODEFS_H */
