/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eAndroidFullscreen.h"


#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
// For MIPs (and WP8) platform we do not have asm code for stack switching
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL_LOCK
#endif
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef    s3eBool(*s3eAndroidFullscreenIsImmersiveSupported_t)();
typedef       void(*s3eAndroidFullscreenOn_t)(s3eBool immersive, s3eBool stickyNavBar, s3eBool staticLayout);
typedef       void(*s3eAndroidFullscreenOff_t)(s3eBool showStatusBar, s3eBool showNavBar, s3eBool staticLayout);

/**
 * struct that gets filled in by s3eAndroidFullscreenRegister
 */
typedef struct s3eAndroidFullscreenFuncs
{
    s3eAndroidFullscreenIsImmersiveSupported_t m_s3eAndroidFullscreenIsImmersiveSupported;
    s3eAndroidFullscreenOn_t m_s3eAndroidFullscreenOn;
    s3eAndroidFullscreenOff_t m_s3eAndroidFullscreenOff;
} s3eAndroidFullscreenFuncs;

static s3eAndroidFullscreenFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x3bb5b1c4, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eAndroidFullscreen");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x3bb5b1c4, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eAndroidFullscreenAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eBool s3eAndroidFullscreenIsImmersiveSupported()
{
    IwTrace(ANDROIDFULLSCREEN_VERBOSE, ("calling s3eAndroidFullscreen[0] func: s3eAndroidFullscreenIsImmersiveSupported"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eBool ret = g_Ext.m_s3eAndroidFullscreenIsImmersiveSupported();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eAndroidFullscreenOn(s3eBool immersive, s3eBool stickyNavBar, s3eBool staticLayout)
{
    IwTrace(ANDROIDFULLSCREEN_VERBOSE, ("calling s3eAndroidFullscreen[1] func: s3eAndroidFullscreenOn"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eAndroidFullscreenOn(immersive, stickyNavBar, staticLayout);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eAndroidFullscreenOff(s3eBool showStatusBar, s3eBool showNavBar, s3eBool staticLayout)
{
    IwTrace(ANDROIDFULLSCREEN_VERBOSE, ("calling s3eAndroidFullscreen[2] func: s3eAndroidFullscreenOff"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eAndroidFullscreenOff(showStatusBar, showNavBar, staticLayout);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
